SCR_EditableEntityCore {
 m_EntityLabels {
  SCR_EditableEntityCoreLabelSetting "{6974AAC6FB4F8AA4}" {
   m_Info SCR_UIInfo "{55B085646DAD3864}" {
    Name "#AR-Faction_CRI"
    Icon "{5B23E6E5E62613E0}UI/Flag/FLag.edds"
   }
   m_Order 2001
   m_LabelType FACTION_CRI
   m_LabelGroupType FACTION
  }
 }
}