SCR_Faction : "{277AE7613D88A55B}Configs/Factions/INDFOR.conf" {
 FactionKey "CRI"
 UIInfo SCR_FactionUIInfo "{6974AAC0BD92B133}" {
  Name "#AR-Faction_CRI"
  Icon "{5B23E6E5E62613E0}UI/Flag/FLag.edds"
  m_sNameUpper "AR-Faction_CRI-UC"
 }
 "Identity of soldiers" FactionIdentity "{570EEB96B808B7E1}" : "{46413880217C8196}Configs/Identities/FactionIdentity_FIA.conf" {
  SoundIdentityArray {
   SoundIdentity "{570EDB84CC3FD4B9}" {
    VoiceID 101
   }
   SoundIdentity "{5B0EABB09D6FA49C}" {
    VoiceID 101
   }
   SoundIdentity "{5B0EABB09346E05D}" {
    VoiceID 101
   }
   SoundIdentity "{5B0EABB088B84F07}" {
    VoiceID 102
   }
   SoundIdentity "{5B0EABB0852FB418}" {
    VoiceID 102
   }
   SoundIdentity "{5B0EABB0BDB4087F}" {
    VoiceID 102
   }
  }
 }
 "Radio encryption key" "Ramzan"
 m_iOrder 2001
 m_OutlineFactionColor 0.001 0.082 0.023 1
 m_sFactionFlag "{5B23E6E5E62613E0}UI/Flag/FLag.edds"
 m_FactionFlagMaterial "{412C2F63690A2576}UI/Flag/Flag_CRI.emat"
 m_FactionLabel FACTION_CRI
 m_CallsignInfo SCR_FactionCallsignInfo "{60A6B21E18F28741}" : "{D7164359D005B37A}Configs/Callsigns/Callsigns_FIA.conf" {
 }
 m_iFactionRadioFrequency 52000
 m_aEntityCatalogs {
  SCR_EntityCatalogMultiList "{5C68A0EABE8B7B2A}" : "{6F6056A597C462CC}Configs/EntityCatalog/FIA/Characters_EntityCatalog_FIA.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68A0EABB80080C}" : "{EBAEEC261D3849A6}Configs/EntityCatalog/FIA/Vehicles_EntityCatalog_FIA.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68A0EAB887A0C4}" : "{2F785E9F5C561C50}Configs/EntityCatalog/FIA/Groups_EntityCatalog_FIA.conf" {
  }
  SCR_EntityCatalog "{5C68A0EAA323888C}" : "{788ADC7B3D869324}Configs/EntityCatalog/FIA/WeaponTripod_EntityCatalog_FIA.conf" {
  }
  SCR_EntityCatalogMultiList "{5C68C44CB0CFC935}" : "{E908001749419691}Configs/EntityCatalog/FIA/InventoryItems_EntityCatalog_FIA.conf" {
  }
  SCR_EntityCatalog "{5C9EDDD370331114}" : "{C9187BDF77D40F34}Configs/EntityCatalog/FIA/SupplyContainerItems_EntityCatalog_FIA.conf" {
  }
 }
}