SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 "Identity of soldiers" FactionIdentity "{570D128F4022EF5A}" {
  VisualIdentityArray {
   VisualIdentity "{68B16540460FC690}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
    Head "{EAF055495BA85CA1}Prefabs/Characters/Heads/Head_White_02.et"
   }
   VisualIdentity "{68B165404C4796BA}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
   }
  }
 }
 m_CallsignInfo SCR_FactionCallsignInfo "{6532BE0F364556A4}" {
  m_bIsAssignedRandomly 0
  m_aCompanyNames {
   SCR_CallsignInfo "{68B10360ED47D743}" {
    m_sCallsign "Aigle"
   }
   SCR_CallsignInfo "{68B10360ECA6DE05}" {
    m_sCallsign "Bastion"
   }
   SCR_CallsignInfo "{68B10360EC86966B}" {
    m_sCallsign "Centurion"
   }
   SCR_CallsignInfo "{68B10360ECE213CB}" {
    m_sCallsign "Dragon"
   }
   SCR_CallsignInfo "{68B10360ECFB23BC}" {
    m_sCallsign "Éclair"
   }
   SCR_CallsignInfo "{68B10360EC345E3B}" {
    m_sCallsign "Faucon"
   }
   SCR_CallsignInfo "{68B10360EC70DC60}" {
    m_sCallsign "Hermine"
   }
  }
  m_aPlatoonNames {
   SCR_CallsignInfo "{68B10360FA4BAF5E}" {
    m_sCallsign "1"
   }
   SCR_CallsignInfo "{68B1036105A6FEB7}" {
    m_sCallsign "2"
   }
   SCR_CallsignInfo "{68B1036105BE01C3}" {
    m_sCallsign "3"
   }
   SCR_CallsignInfo "{68B10361059887CE}" {
    m_sCallsign "4"
   }
   SCR_CallsignInfo "{68B1036105F104E1}" {
    m_sCallsign "5"
   }
   SCR_CallsignInfo "{68B1036105CD5DF5}" {
    m_sCallsign "6"
   }
   SCR_CallsignInfo "{68B10361050C201C}" {
    m_sCallsign "7"
   }
  }
  m_aSquadNames {
   SCR_CallsignInfo "{68B1036102C1DFAC}" {
    m_sCallsign "1"
   }
   SCR_CallsignInfo "{68B1036102D8087B}" {
    m_sCallsign "2"
   }
   SCR_CallsignInfo "{68B103610231751F}" {
    m_sCallsign "3"
   }
   SCR_CallsignInfo "{68B10361020EB925}" {
    m_sCallsign "4"
   }
   SCR_CallsignInfo "{68B1036102639B6D}" {
    m_sCallsign "5"
   }
   SCR_CallsignInfo "{68B10361027BD8BA}" {
    m_sCallsign "6"
   }
   SCR_CallsignInfo "{68B103610DCDE903}" {
    m_sCallsign "7"
   }
  }
  m_sCallsignGroupFormat "%1 %2–%3"
  m_sCallsignCharacterFormat "%1 %2 %3: %4"
 }
}