SCR_Faction : "{E7B7EA4823DD81F0}Configs/Factions/BLUFOR.conf" {
 "Identity of soldiers" FactionIdentity "{570D128F4022EF5A}" {
  VisualIdentityArray {
   VisualIdentity "{68C6E6038B90D2D7}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
    Head "{EAF055495BA85CA1}Prefabs/Characters/Heads/Head_White_02.et"
    Headcamo {
     "{7E7987E31FB379BF}Prefabs/Characters/Heads/Head_White_10/Head_White_10_camo_US_01.et"
     "{3A4B78A288F46331}Prefabs/Characters/Heads/Head_White_10/Head_White_10_camo_US_02.et"
    }
   }
   VisualIdentity "{68C6E603822D30B6}" : "{FAE42E51C156837C}Configs/Identities/VisualIdentity_base.conf" {
    Headcamo {
     "{7E7987E31FB379BF}Prefabs/Characters/Heads/Head_White_10/Head_White_10_camo_US_01.et"
     "{3A4B78A288F46331}Prefabs/Characters/Heads/Head_White_10/Head_White_10_camo_US_02.et"
    }
   }
  }
 }
}