MagazineConfig {
 AmmoResourceArray {
  "{5A2E0AD043840F2A}Prefabs/Weapons/Ammo/30x165/Ammo_30mm_APT_3UBR6.et"
  "{02ACD01C0FEF1D99}Prefabs/Weapons/Ammo/30x165/Ammo_30mm_APFSDS_3UBR11.et"
  "{2463839CB2700402}Prefabs/Weapons/Ammo/30x165/Ammo_30mm_HEFI_3UOF8.et"
  "{53A412B956DD26A4}Prefabs/Weapons/Ammo/30x165/Ammo_30mm_HEFT_3UOR6.et"
 }
}