WeatherStateMachine {
 States {
  SCR_WeatherState "{663D0BE30386C80A}" {
   WeatherVariant0 WeatherVariant "{555888011627D6AF}" {
    FogPattern WeatherFogPattern "{6178DD5554EBC2DA}" {
     FogMinAmount 0.9
     FogMaxAmount 0.9
    }
   }
  }
  SCR_WeatherState "{6636F14BE488360D}" {
   WeatherVariant0 WeatherVariant "{555888011627D6AF}" {
    FogPattern WeatherFogPattern "{6178DD5554EBC2DA}" {
     FogMinAmount 0.9
    }
   }
  }
  SCR_WeatherState "{655A740758DEA487}" {
   WeatherVariant0 WeatherVariant "{56248BCDA0315911}" {
    FogPattern WeatherFogPattern "{61B6B2FA16D667E0}" {
     FogMinAmount 0.8
     FogMaxAmount 0.9
    }
   }
  }
  SCR_WeatherState "{655A740758DEA4A4}" {
   WeatherVariant0 WeatherVariant "{55588801387B7AC2}" {
    FogPattern WeatherFogPattern "{61B6B2FBDACEF58D}" {
     FogMinAmount 0.8
     FogMaxAmount 0.9
    }
   }
  }
 }
}